chatfrontend:
  image:
    repository: baylon44/redis-chat-frontend
<<<<<<< HEAD
    tag: 11188071233
=======
    tag: 11059342719
>>>>>>> 20b5ba6568264090c2984c67246a60daf39778b8
  service:
    type: ClusterIP
    port: 3000

chatbackend:
  image:
    repository: baylon44/redis-chat-backend
<<<<<<< HEAD
    tag: 11188071233
=======
    tag: 11059342719
>>>>>>> 20b5ba6568264090c2984c67246a60daf39778b8
  service:
    type: ClusterIP
    port: 8000

redis:
  image:
    repository: redis
    tag: alpine
  service:
    type: ClusterIP
    port: 6379
