chatfrontend:
  image:
    repository: baylon44/redis-chat-frontend
    tag: 10936501657
  service:
    type: ClusterIP
    port: 3000

chatbackend:
  image:
    repository: baylon44/redis-chat-backend
    tag: 10936501657
  service:
    type: ClusterIP
    port: 8000

redis:
  image:
    repository: redis
    tag: alpine
  service:
    type: ClusterIP
    port: 6379
