FROM node:16-alpine 

# Set the working directory inside the container
WORKDIR /app

# Copy package.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application 
RUN npm run build

# Ensure /bin/sh is available
RUN apk add --no-cache bash

# Expose the application port 
EXPOSE 5000

# Set the command to run the application
CMD ["npm", "start"]
