services:
  chatfrontend:
    build:
      context: ./client
      dockerfile: dockerfile
    image: baylon44/redis-chat-app:chatfrontend.v2
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://chatbackend:8000
    depends_on:
      - chatbackend
    networks:
      - redis-net

  chatbackend:
    build:
      context: .
      dockerfile: Dockerfile
    image: baylon44/redis-chat-app:chatbackend.v3
    restart: always
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://:redispass@redis:6379/0
      - CREATE_DEMO_DATA=True
    depends_on:
      - redis
    networks:
      - redis-net

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redispass #for development purposes
    command: redis-server --requirepass redispass
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - redis-net

volumes:
  redis-data:

networks:
  redis-net:
    driver: bridge