services:
  chatfrontend:
    build:
      context: ./client
      dockerfile: dockerfile
    tty: true
    ports:
      - "5000:5000"
    depends_on:
      - chatbackend
    networks:
     - redis-net

  chatbackend:
    build:
      context: . 
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL = redis://redisuser:redispass@redis:6379/0
    depends_on:
      - redis
    networks:
      - redis-net
    
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - REDIS_USERNAME=redisuser
      - REDIS_PASSWORD=redispass
    command: redis-server --requirepass redispass --masterauth redispass
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  redis-net: