apiVersion: v1
kind: Service
metadata:
  name: chatfrontend-service
spec:
  selector:
    app: redis-chat-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

--- 