apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-chat-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  ingressClassName: nginx
  rules:
  - host: redis-chat.local
    http:
      paths:
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: chatfrontend-service
            port:
              number: 3000
      - path: /backend
        pathType: Prefix
        backend:
          service:
            name: chatbackend-service
            port:
              number: 8000
--- 