apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbackend
  labels:
    app: chatbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbackend
  template:
    metadata:
      labels:
        app: chatbackend
    spec:
      containers:
      - name: chatbackend
        image: baylon44/redis-chat-app:chatbackend.v3
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
        - name: CREATE_DEMO_DATA
          value: "true"
          
---