apiVersion: v1
kind: Service
metadata:
  name: chatfrontend-service
spec:
  selector:
    app: chatfrontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: {{ .Values.chatfrontend.service.type }}

--- 