apiVersion: v1
kind: Service
metadata:
  name: chatbackend-service
spec:
  selector:
    app: chatbackend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: {{ .Values.chatbackend.service.type }}